export default {
    png0: require('../assets/0.png'),
    png1: require('../assets/1.png'),
    png2: require('../assets/2.png'),
    png3: require('../assets/3.png'),
    portrait0: require('../assets/people/0.png'),
    portrait1: require('../assets/people/1.png'),
    portrait2: require('../assets/people/2.png'),
    photo00: require('../assets/commentPhotos/0/0.png'),
    photo01: require('../assets/commentPhotos/0/1.png'),
    photo02: require('../assets/commentPhotos/0/2.png'),
    photo10: require('../assets/commentPhotos/1/0.png'),
    photo20: require('../assets/commentPhotos/2/0.png'),
    photo21: require('../assets/commentPhotos/2/1.png'),
    photo22: require('../assets/commentPhotos/2/2.png'),
    photo23: require('../assets/commentPhotos/2/3.png'),
    photo24: require('../assets/commentPhotos/2/4.png'),
}